# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 983f6ecaeed7e898dab32527d08687d3fab41b855b1398ad3b64dc73dab144e66ac0770a79b018a5062a165ac42db283fa872d00b5f88c041ed2526be91ae711

test:
  secret_key_base: bfece4d97714f3c4af20f45ae51308c6cefce8c8430f78fdeff38997a2b08d1089779ab81adca108479012f20a0b3292b902971c5a457be992e33022c227dc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
